export const APP_COMMANDS = {
  appAbout: "app.about",
  appNewWindow: "app.newWindow",
  appQuit: "app.quit",
  editCopy: "edit.copy",
  editCut: "edit.cut",
  editFind: "edit.find",
  editFindNext: "edit.findNext",
  editFindPrevious: "edit.findPrevious",
  editPaste: "edit.paste",
  editRedo: "edit.redo",
  editSelectAll: "edit.selectAll",
  editUndo: "edit.undo",
  editorInsertCodeFence: "editor.insertCodeFence",
  editorInsertTable: "editor.insertTable",
  fileClose: "file.close",
  fileCopyPath: "file.copyPath",
  fileDelete: "file.delete",
  fileDuplicate: "file.duplicate",
  fileMove: "file.move",
  fileNewFile: "file.newFile",
  fileNewFolder: "file.newFolder",
  fileOpenFile: "file.openFile",
  fileOpenFolder: "file.openFolder",
  fileRename: "file.rename",
  fileRevealInFinder: "file.revealInFinder",
  fileSave: "file.save",
  fileSaveAs: "file.saveAs",
  formatBold: "format.bold",
  formatClearFormat: "format.clearFormat",
  formatCode: "format.code",
  formatCodeFence: "format.codeFence",
  formatHeading1: "format.heading1",
  formatHeading2: "format.heading2",
  formatHeading3: "format.heading3",
  formatHeading4: "format.heading4",
  formatHeading5: "format.heading5",
  formatHeading6: "format.heading6",
  formatInsertImage: "format.insertImage",
  formatItalic: "format.italic",
  formatLink: "format.link",
  formatMathBlock: "format.mathBlock",
  formatOrderedList: "format.orderedList",
  formatParagraph: "format.paragraph",
  formatQuote: "format.quote",
  formatTaskList: "format.taskList",
  formatUnderline: "format.underline",
  formatUnorderedList: "format.unorderedList",
  repositoryConnectGithub: "repository.connectGithub",
  repositoryDisconnectGithub: "repository.disconnectGithub",
  repositoryLinkWorkspace: "repository.linkWorkspace",
  repositoryPullWorkspace: "repository.pullWorkspace",
  repositoryPushWorkspace: "repository.pushWorkspace",
  repositorySyncNow: "repository.syncNow",
  repositoryViewSyncStatus: "repository.viewSyncStatus",
  themeDark: "theme.dark",
  themeLight: "theme.light",
  viewEdit: "view.edit",
  viewFileTree: "view.fileTree",
  viewLiveEdit: "view.liveEdit",
  viewPreview: "view.preview",
  viewResetZoom: "view.resetZoom",
  viewSourceCode: "view.sourceCode",
  viewSplit: "view.split",
  viewToggleSidebar: "view.toggleSidebar",
  viewZoomIn: "view.zoomIn",
  viewZoomOut: "view.zoomOut",
  workspaceCollapseAll: "workspace.collapseAll",
  workspaceRefresh: "workspace.refresh"
} as const;

export type AppCommandId = typeof APP_COMMANDS[keyof typeof APP_COMMANDS];

const appCommandIdSet = new Set<string>(Object.values(APP_COMMANDS));

export function isAppCommandId(value: string): value is AppCommandId {
  return appCommandIdSet.has(value);
}
