export const TAURI_COMMANDS = {
  copyImageAsset: "copy_image_asset",
  createMarkdownFile: "create_markdown_file",
  createWorkspaceDirectory: "create_workspace_directory",
  deleteWorkspaceEntry: "delete_workspace_entry",
  duplicateWorkspaceEntry: "duplicate_workspace_entry",
  exportPngFile: "export_png_file",
  exportSvgFile: "export_svg_file",
  listWorkspaceFiles: "list_workspace_files",
  loadMarkdownFile: "load_markdown_file",
  moveEntry: "move_entry",
  openExternalUrl: "open_external_url",
  openMarkdownFile: "open_markdown_file",
  openNewAppWindow: "open_new_app_window",
  refreshWorkspaceSyncIndex: "refresh_workspace_sync_index",
  renameEntry: "rename_entry",
  repositoryConnectProvider: "repository_connect_provider",
  repositoryDisconnectProvider: "repository_disconnect_provider",
  repositoryGetAccount: "repository_get_account",
  repositoryGetSyncStatus: "repository_get_sync_status",
  repositoryGetWorkspaceBinding: "repository_get_workspace_binding",
  repositoryLinkWorkspace: "repository_link_workspace",
  repositoryListRepositories: "repository_list_repositories",
  repositoryPullWorkspace: "repository_pull_workspace",
  repositoryPushWorkspace: "repository_push_workspace",
  repositorySyncNow: "repository_sync_now",
  resolveMarkdownAsset: "resolve_markdown_asset",
  revealInFileManager: "reveal_in_file_manager",
  saveImageAsset: "save_image_asset",
  saveMarkdownFile: "save_markdown_file",
  setAppZoom: "set_app_zoom",
  writeMarkdownFile: "write_markdown_file"
} as const;

export type TauriCommandId = typeof TAURI_COMMANDS[keyof typeof TAURI_COMMANDS];
